# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b7410abd25ebb9a88bb360204b9b8d8"
name = "Tap2Share"
handle = "customizer-39"
application_url = "https://reasonably-behind-planet-freely.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/gdpr/webhooks/customer_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/gdpr/webhooks/shop_data_delete"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customer_data_delete"
  compliance_topics = [ "customers/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://reasonably-behind-planet-freely.trycloudflare.com/auth/callback",
  "https://reasonably-behind-planet-freely.trycloudflare.com/auth/shopify/callback",
  "https://reasonably-behind-planet-freely.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://reasonably-behind-planet-freely.trycloudflare.com/storefront/subscription"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true

automatically_update_urls_on_dev = true

