# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b14298e0daadbc2084bd859745a15091"
application_url = "https://detect-mc-planet-gotta.trycloudflare.com"
embedded = true
name = "app-settings"
handle = "app-settings-1"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://detect-mc-planet-gotta.trycloudflare.com/auth/callback",
  "https://detect-mc-planet-gotta.trycloudflare.com/auth/shopify/callback",
  "https://detect-mc-planet-gotta.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://detect-mc-planet-gotta.trycloudflare.com/storefront/subscription"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
