# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "20f31d269398d5f23df95d0450e772e9"
name = "test-app"
handle = "test-app-11537"
application_url = "https://began-clicking-gratis-tile.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://began-clicking-gratis-tile.trycloudflare.com/auth/callback",
  "https://began-clicking-gratis-tile.trycloudflare.com/auth/shopify/callback",
  "https://began-clicking-gratis-tile.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
